# cloudbuild.yaml
substitutions:
  _SERVICE: "cms-backend-service"
  _IMAGE:   "mock-vle"
  _REGION:  "us-central1"

steps:
- name: "gcr.io/cloud-builders/docker"
  args:
    - build
    - -t
    - "gcr.io/$PROJECT_ID/${_IMAGE}:latest"
    - .

- name: "gcr.io/cloud-builders/docker"
  args:
    - push
    - "gcr.io/$PROJECT_ID/${_IMAGE}:latest"

- name: "gcr.io/cloud-builders/gcloud"
  args:
    - run
    - deploy
    - "${_SERVICE}"
    - --image=gcr.io/${PROJECT_ID}/${_IMAGE}:latest
    - --region=${_REGION}
    - --platform=managed
    - --allow-unauthenticated
    - --quiet

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE}:latest"

timeout: "1200s"
